name: C windows CI

on: [push]

jobs:
  # Building using the GitHub runner environment directly.
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name : Show directory
      run : cd
    - name: Compile
      run : gcc Register2023.c -o Permalized/AIassignmentRegister2023/Register2023.exe
