name: C windows CI

on: [push]

jobs:
  # Building using the GitHub runner environment directly.
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name : Show directory
      run : cd
    - name: Compile
      run : gcc Register2023.c -o D:\a\AIassignmentRegister2023\AIassignmentRegister2023\result.exe
    - name : Changing Directories
      run : cd D:\a\AIassignmentRegister2023\AIassignmentRegister2023
    - name : Showing files in directory
      run : ls
